src/classes/index.ts, src/classes/obligation.ts, tests/market.test.ts
=> :memo: Expose non ltv 0 total deposits

.github/workflows/release_action.yml
=> :bug: Fix release action not showing up in github

src/classes/reserve.ts, tests/obligation.test.ts, tests/reserve.test.ts
=> :memo: Add protocol take rate calc

src/classes/reserve.ts
=> :memo: Include take rate in simulated supply APR

src/lending_operations/repay_with_collateral_operations.ts, src/leverage/operations.ts, tests/assert.ts, tests/leverage.test.ts, tests/leverage_utils.ts, tests/repay_with_coll.test.ts, tests/repay_with_coll_utils.ts
=> Add swapInputs calcs and tests

src/leverage/operations.ts, tests/leverage.test.ts
=> Make swapInputs inputs decimal lmaports 

src/lending_operations/repay_with_collateral_operations.ts, src/leverage/instructions.ts, src/leverage/operations.ts, src/utils/userMetadata.ts
=> Add programId to missing multiply logic

src/classes/action.ts, src/classes/market.ts, src/classes/obligation.ts, src/classes/reserve.ts
=> Calculate deposit interest on obligations

package.json
=> Link sdk to source repo

.github/workflows/test.yml, src/classes/reserve.ts, tests/reserve_calcs.test.ts
=> Fix compound interest calculation

src/idl_codegen/zero_padding/ObligationZP.ts, src/idl_codegen/zero_padding/README.md, src/idl_codegen/zero_padding/index.ts, src/lib.ts, tests/zero_padding.test.ts
=> Optimisation - Add Obligation with padding removed

src/classes/obligation.ts
=> Fix obligation deposit calcs - do not floor $ value

src/utils/seeds.ts
=> :bug: Fix referrer token state pda wrongly passed

.github/workflows/release_action.yml, README.md, package.json
=> Migrate to kamino namespace

package.json, src/classes/market.ts, src/utils/rpc.ts, tests/market.test.ts, tests/obligation.test.ts, yarn.lock
- Fix `KaminoMarket.getAllObligationsForMarket` - use zstd to reduce response string length to below nodejs limits
- Request zero-padding obligation to save memory
- Fix `performs_a_repay_and_withdraw_same_tx` test
=> Fix `KaminoMarket.getAllObligationsForMarket` - use zstd to reduce response string length to below nodejs limits

src/idl.json, src/idl_codegen/accounts/LendingMarket.ts, src/idl_codegen/accounts/Obligation.ts, src/idl_codegen/errors/custom.ts, src/idl_codegen/instructions/index.ts, src/idl_codegen/instructions/updateSingleReserveConfig.ts, src/idl_codegen/types/ReserveConfig.ts, src/idl_codegen/types/UpdateConfigMode.ts, src/idl_codegen/types/UpdateLendingMarketConfigValue.ts, src/idl_codegen/types/UpdateLendingMarketMode.ts, src/idl_codegen/types/index.ts, src/idl_codegen/zero_padding/ObligationZP.ts
=> :memo: Update codegen for latest release

src/lending_operations/repay_with_collateral_calcs.ts, src/lending_operations/repay_with_collateral_operations.ts, tests/repay_with_coll.test.ts
=> Fix repay_with_coll issues

src/classes/reserve.ts, src/lending_operations/repay_with_collateral_calcs.ts, src/lending_operations/repay_with_collateral_operations.ts
=> Parametrised repay-w-coll

src/utils/userMetadata.ts
=> Add obligation to repay with coll user luts

src/lending_operations/repay_with_collateral_operations.ts
=> Return input data for debugger

src/classes/market.ts, src/referrals/operations.ts
=> 🩹 Fix wrongly returned market TVL

src/classes/obligation.ts
This patch prevents side effects during obligation stats simulations.
=> prevent position mutation in simulations

src/leverage/calcs.ts, tests/leverage_calcs.test.ts, tests/leverage_utils.ts
=> feat: use async function to get prices in calculateMultiplyEffects

src/classes/market.ts
=> ♿️ Helper to display min net value obligation

src/classes/market.ts, src/classes/reserve.ts, tests/reserve_calcs.test.ts, tests/setup_utils.ts
=> Add recent slot duration adjustment

tests/farms_tests/init_refresh_farm_deposit_borrow_and_repay_withdraw.test.ts
=> Fix import

src/classes/reserve.ts, tests/market.test.ts, tests/reserve_calcs.test.ts
=> 🩹 Fix missing calc on compound interest

package.json, yarn.lock
=> Update farms dependency

src/classes/obligation.ts, tests/market.test.ts
=> 🐛 Fix disable usage coll outside emode borrow max

src/classes/reserve.ts
=> 🐛 Fix big fraction formula

src/leverage/operations.ts
=> 🩹 Fix scope refresh in multiply

src/classes/action.ts, src/leverage/operations.ts
=> 🐛 Fix wrong token program passed for multiply

src/classes/action.ts
=> 🐛 Fix retrieval of deposit reserve for emode

package.json, tests/setup_utils.ts, yarn.lock
=> 🔥 Remove unused deps

src/classes/action.ts, src/classes/obligation.ts, tests/market.test.ts, tests/obligation.test.ts
=> ✨ Add option to request emode for vanilla borrowing

package.json, yarn.lock
=> Migrate `@hubbleprotocol/kamino-sdk` -> `@kamino-finance/kliquidity-sdk`

src/classes/action.ts, tests/obligation.test.ts
=> 🚩 Set emode to 0 after full repay

src/classes/obligation.ts, tests/market.test.ts
=> Fix dual-action estimation logic

src/classes/action.ts, src/classes/obligation.ts
=> 👷 Account for case when emode is not set

src/classes/market.ts, src/classes/obligation.ts, tests/leverage.test.ts, tests/market.test.ts
=> ♻️ Abstract elevation group passing from max borrow fn

src/classes/action.ts, src/classes/obligation.ts, src/lending_operations/repay_with_collateral_operations.ts, tests/farms_tests/init_refresh_farm_repay.test.ts, tests/repay_with_coll.test.ts, tests/setup_utils.ts
=> 🐛 Fix bugs related to farms ix appending

src/classes/obligation.ts, tests/market.test.ts
=> Pass correct mint for getSimulatedObligationStats

src/classes/reserve.ts
=> ♻️ Display proper simulated borrow apr
